GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public."user" TO test;
GRANT INSERT, SELECT, UPDATE ON TABLE public.refresh_token TO test;
GRANT INSERT, SELECT, UPDATE ON TABLE public.access_token TO test;