GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.account TO test;

GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.profile TO test;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.profile_contact TO test;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.profile_rating TO test;